spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres.xobkqehriftlivzczqki}
spring.datasource.password=${DB_PASSWORD:MiniProjectAutoWash}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration
washmate.database.migration-runner.enabled=false

washmate.security.jwt.secret=${JWT_SECRET:washmate-secret-at-least-32-characters-long}
washmate.security.allowed-origin-patterns=${CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:*,http://127.0.0.1:*}
washmate.loyalty.rollback.enabled=${LOYALTY_ROLLBACK_ENABLED:false}
washmate.supabase.url=${SUPABASE_URL:}
washmate.supabase.service-role-key=${SUPABASE_SERVICE_ROLE_KEY:}
washmate.supabase.storage.avatar-bucket=${SUPABASE_AVATAR_BUCKET:avatars}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

washmate.payment.vnpay.enabled=${VNPAY_ENABLED:true}
washmate.payment.vnpay.tmn-code=${VNPAY_TMN_CODE:9PKMIU2S}
washmate.payment.vnpay.hash-secret=${VNPAY_HASH_SECRET:DVQ5AT0ZGI7ZJMCKXXO9B8IY3UXEHIXA}

spring.mail.host=${MAIL_HOST:smtp.resend.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:resend}
spring.mail.password=${MAIL_PASSWORD:re_QaroeqzJ_2QuHTdjPrMcVHH5xSxYa2bx8}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
